name: checksumchecker
version: '1.0'
summary: Verify and generate checksums for files on Linux
description: |
  A simple GUI application to verify and generate checksums for files on Linux
grade: stable
confinement: devmode
license: MIT
base: core24

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
    
apps:
  checksumchecker:
    command: checksum_checker
    extensions:
      - kde-neon-6
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONPATH: $SNAP/lib/python3.12/site-packages
      LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/lib:$SNAP/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
    plugs:
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - network
      - wayland
      - x11
            
parts:
  checksumchecker:
    source: https://github.com/kz6fittycent/checksum_checker
    source-type: git
    plugin: python

  launcher:
    plugin: dump
    source: scripts
