name: checksumchecker
#adopt-info: checksumchecker
version: '1.0'
summary: Verify and generate checksums for files on Linux.
description: |
  A simple GUI application to verify and generate checksums for files on Linux.
  
grade: stable
confinement: strict
license: MIT
base: core24

platforms:
  build-for: [all]
  

apps:
  checksumchecker:
    command: checksum_checker
    extensions:
      - gnome    
    plugs:
      - home
      - removable-media
            
parts:
  checksumchecker:
    source: https://github.com/kz6fittycent/checksum_checker
    source-type: git
    plugin: python
    
    stage-packages:
      - python3
      - python3-pyqt6
    
#    override-pull: |
#      craftctl default
#      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"    

  launcher:
    plugin: dump
    source: scripts
