name: checksumchecker
version: '1.0'
summary: Verify and generate checksums for files on Linux
description: |
  A simple GUI application to verify and generate checksums for files on Linux
grade: stable
confinement: devmode
license: MIT
base: core24

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
    
apps:
  checksumchecker:
    command: checksum_checker
    extensions:
      - gnome
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONPATH: $SNAP/lib/python3.12/site-packages
      LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/lib:$SNAP/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
    plugs:
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - network
      - wayland
      - x11
            
parts:
  checksumchecker:
    source: https://github.com/kz6fittycent/checksum_checker
    source-type: git
    plugin: python
    build-packages:
      - qt6-base-dev
      - qmake6
      - libxcb-cursor0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-render-util0
      - libxcb-shape0
      - libmysqlclient-dev
      - libpq5
      - python3-dev
      - python3-venv
      - libproxy1v5
      - libglib2.0-dev
    stage-packages:
      - qt6-base-dev
      - libxcb-cursor0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-render-util0
      - libxcb-shape0
      - libmysqlclient-dev
      - libpq5
      - libproxy1v5
      - libglib2.0-0
      - libqt6dbus6
    python-packages:
      - PyQt6==6.4.2
    override-build: |
      # Create a virtual environment and set PATH to include qmake
      python3 -m venv venv
      export PATH="/usr/lib/qt6/bin:$PATH"
      # Install PyQt6 from source with qmake available
      ./venv/bin/pip install --no-binary :all: PyQt6==6.4.2
      # Copy the virtual environment to the part install
      cp -r venv/lib/python3.12/site-packages/* $CRAFT_PART_INSTALL/lib/python3.12/site-packages/
      # Ensure Qt plugins are staged
      cp -r $CRAFT_STAGE/usr/lib/x86_64-linux-gnu/qt6/plugins $CRAFT_PART_INSTALL/lib/qt6/plugins/
      # Copy Qt libraries
      cp -r $CRAFT_STAGE/usr/lib/x86_64-linux-gnu/libQt6* $CRAFT_PART_INSTALL/lib/
      craftctl default
    override-prime: |
      # Keep only necessary Qt plugins and libraries
      rm -rf $CRAFT_PRIME/lib/qt6/plugins/*/*_debug*
      rm -rf $CRAFT_PRIME/lib/libQt6Labs*.so*
      rm -rf $CRAFT_PRIME/lib/libQt6Quick3D*.so*
      craftctl default

  launcher:
    plugin: dump
    source: scripts
