name: checksumchecker
adopt-info: checksumchecker
summary: Verify and generate checksums for files on Linux
description: |
  A simple GUI application to verify and generate checksums for files on Linux
grade: stable
confinement: strict
license: MIT
base: core24
compression: lzo

website: https://github.com/kz6fittycent/checksum_checker
contact: https://github.com/kz6fittycent/checksum_checker/issues
issues: https://github.com/kz6fittycent/checksum_checker/issues
source-code: https://github.com/kz6fittycent/checksum_checker
icon: snap/gui/checksum_checker.png
donation: https://www.patreon.com/kz6fittycent

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
    
apps:
  checksumchecker:
    command: checksum_checker
    extensions:
      - kde-neon-6
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONPATH: $SNAP/lib/python3.12/site-packages
      LD_LIBRARY_PATH: $SNAP/lib/python3.12/site-packages/PyQt6/Qt6:$SNAP/kf6/usr/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:$SNAP/usr/lib:$SNAP/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
      QT_PLUGIN_PATH: $SNAP/lib/python3.12/site-packages/PyQt6/Qt6/plugins/platforms
      QT_STYLE_OVERRIDE: Fusion:dark
    plugs:
      - home
      - removable-media
      - network

parts:
  checksumchecker:
    source: https://github.com/kz6fittycent/checksum_checker
    source-type: git
    plugin: python
    python-packages: 
      - PyQt6==6.5.0
    build-packages:
      - libxcb-cursor0
      - qt6-base-dev 

    stage-packages:
      - libxcb-cursor0    
      
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"

  launcher:
    plugin: dump
    source: scripts
